# Generated by Django 5.0.4 on 2024-05-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('cpassword', models.CharField(max_length=100, verbose_name='confirm password')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is_admin')),
                ('is_user', models.BooleanField(default=False, verbose_name='is_user')),
            ],
        ),
    ]
