# Generated by Django 5.0.4 on 2024-05-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_signup_cpassword_alter_signup_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='is_user',
        ),
        migrations.AddField(
            model_name='signup',
            name='role',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='cpassword',
            field=models.CharField(default='0000', max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(default='user@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(default='0000', max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
